services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/home/app/web
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=project/__init__.py
    depends_on:
      - db
      - common_python

