version: '3.7'

services:
  downloader_cc:
    build: ./services/downloader_cc
    volumes:
      - /data/common-crawl:/data/common-crawl
      - ./services/downloader_cc/:/home/app
    env_file:
      - ./.env.prod

networks:
  default:
    name: novichenko
