version: '3.7'

services:
  common_python:
    build: ./services/common_python
    image: common_python
    command: echo 'success'
  db:
    image: edoburu/pgbouncer:1.15.0
    environment:
      - DB_HOST=pg
    env_file:
      - ./.env.prod
    depends_on:
      - pg
  pg:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
        # - postgres_wal:/var/lib/postgresql/data/pg_wal/
        - postgres_fastdata:/fastdata
        - novichenko:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

networks:
  default:
    name: novichenko

volumes:
  novichenko:
  postgres_fastdata:
