version: '3.7'

services:
  common_python:
    build: ./services/common_python
    image: common_python
    command: echo 'success'
  db:
    image: edoburu/pgbouncer:1.15.0
    environment:
      - DB_HOST=pg
    env_file:
      - ./.env.prod
    depends_on:
      - pg
  pg:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    shm_size: 16gb
    labels: ['com.citusdata.role=Master']
    volumes:
      - /home/usertest/pg_volume:/var/lib/postgresql/data/
        #- /home/usertest/bigdata/pg_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env.prod

networks:
  default:
    name: novichenko
