version: '3.7'

services:
  common_python:
    build: ./services/common_python
    image: common_python
    command: echo 'success'
  db:
    image: edoburu/pgbouncer:1.15.0
    environment:
      - DB_HOST=pg
    env_file:
      - ./.env.prod
    depends_on:
      - pg
  pg:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    labels: ['com.citusdata.role=Master']
    #volumes:
        # - novichenko_fastdata:/fastdata
        # - novichenko_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env.prod

  citus_worker:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    labels: ['com.citusdata.role=Worker']
    deploy:
      replicas: 8
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env.prod
    depends_on: [pg]

networks:
  default:
    name: novichenko

#volumes:
#  novichenko_data:
#  novichenko_fastdata:
