import time
from sqlalchemy.sql import text
from flask import Flask, send_from_directory, g, request
import flask


def render_template(name, **kwargs):
    '''
    like the flask render_template function, but also passes the debug information generated by calls to the do_query function
    '''
    return flask.render_template(
        name,
        queries=g.queries,
        **kwargs
        )


def do_query(name, sql, binds):
    '''
    performs a query with the database and records debug information that will be stored for later
    '''
    start = time.time()
    res = list(g.connection.execute(text(sql), binds))
    explain = '\n'.join(map(lambda x:x[0], g.connection.execute(text('explain '+sql), binds)))
    stop = time.time()
    g.queries.append({
        'name': name,
        'sql': sql,
        'binds': binds,
        'runtime': stop-start,
        'explain': str(explain),
        })
    return res

